package com.smartvision.gallery.privacy

import android.content.Context
import android.net.Uri
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.biometric.BiometricManager
import androidx.biometric.BiometricPrompt
import androidx.core.content.ContextCompat
import androidx.fragment.app.FragmentActivity
import com.smartvision.gallery.R
import com.smartvision.gallery.data.model.MediaItem
import com.smartvision.gallery.data.repo.MediaRepository
import com.smartvision.gallery.util.AppLog
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.security.KeyStore
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Privacy vault with **real on-device encryption**.
 *
 *  * Hidden items are AES-GCM-encrypted with a per-vault master key generated by
 *    [KeyGenParameterSpec] inside the **AndroidKeyStore**. The key never leaves
 *    secure storage; we only get a [Cipher] back from it, encrypted with the
 *    device-bound hardware key where available.
 *
 *  * Encrypted bytes are stored in `cacheDir/.vault/<original-uri-hash>.enc` along
 *    with a sidecar `.meta` file that records the original display name + the IV
 *    used for AES-GCM.
 *
 *  * Biometric authentication is provided by [BiometricPrompt] on Android P+. On
 *    devices without biometrics we fall back to device-credential (PIN/pattern/
 *    password).
 *
 *  * On the database side, items are flagged `isHidden = true` so they never
 *    appear in the timeline; the actual encrypted blobs live on disk.
 */
class EncryptedPrivacyVault(
    private val app: Context,
    private val repository: MediaRepository
) {

    private val vaultDir: File by lazy {
        File(app.cacheDir, VAULT_DIR).apply { mkdirs() }
    }

    /** Returns true when biometric / device-credential auth is available. */
    fun canAuthenticate(activity: FragmentActivity): BiometricAvailability {
        val mgr = BiometricManager.from(activity)
        return when (mgr.canAuthenticate(BIOMETRIC_OR_DEVICE_CREDENTIAL)) {
            BiometricManager.BIOMETRIC_SUCCESS -> BiometricAvailability.Available
            BiometricManager.BIOMETRIC_ERROR_NO_HARDWARE -> BiometricAvailability.NoHardware
            BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED -> BiometricAvailability.NotEnrolled
            else -> BiometricAvailability.Unavailable
        }
    }

    /**
     * Encrypts [item] and writes the ciphertext + metadata to the vault. On
     * success the item is also marked `isHidden = true` in Room.
     *
     * Order of operations (reserve-first-then-write):
     *  1. Reserve a fresh SecureRandom vaultId in the DB row
     *  2. Encrypt plaintext + write the .enc / .meta sidecars under that vaultId
     *  3. Flip isHidden = 1 only after both files succeed
     *
     * If anything between (1) and (3) throws we delete the on-disk files and
     * clear the reserved vaultId so the row returns to a clean state.
     */
    suspend fun hide(item: MediaItem): Result<VaultResult> = withContext(Dispatchers.IO) {
        runCatching {
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key) }
            val iv = cipher.iv

            val plainBytes = app.contentResolver.openInputStream(item.uri)?.use { it.readBytes() }
                ?: error("Could not read ${item.uri}")

            val vaultId = generateVaultId()
            // 1. reserve vaultId to DB FIRST
            repository.reserveVaultId(item.uri, vaultId)

            try {
                // 2. 加密 + 写文件
                val cipherBytes = cipher.doFinal(plainBytes)
                val outFile = File(vaultDir, "$vaultId.enc")
                FileOutputStream(outFile).use { it.write(cipherBytes) }

                val metaFile = File(vaultDir, "$vaultId.meta")
                // M15: opaque Base64 metadata to avoid plaintext name/size/iv
                // (the actual key lives in AndroidKeyStore and is never persisted).
                val nameEncoded = android.util.Base64.encodeToString(
                    item.displayName.toByteArray(Charsets.UTF_8),
                    android.util.Base64.NO_WRAP
                )
                val ivEncoded = android.util.Base64.encodeToString(
                    iv,
                    android.util.Base64.NO_WRAP
                )
                val metaText = buildString {
                    append("n=").append(nameEncoded).append('\n')
                    append("s=").append(plainBytes.size).append('\n')
                    append("i=").append(ivEncoded)
                }
                FileOutputStream(metaFile).use { it.write(metaText.toByteArray(Charsets.UTF_8)) }

                // 3. 最后 set DB hidden flag
                repository.setHidden(item.uri, true)
                VaultResult.Hidden(vaultId)
            } catch (t: Throwable) {
                // 4. 任何步骤失败 → 回滚
                File(vaultDir, "$vaultId.enc").delete()
                File(vaultDir, "$vaultId.meta").delete()
                repository.clearVaultId(item.uri)
                throw t
            }
        }.onFailure { AppLog.e(TAG, "Vault.hide failed for ${item.uri}", it) }
            .recoverCatching { throw VaultException.HideFailed(it) }
    }

    /**
     * Removes a hidden item from the vault using its reserved [MediaItem.vaultId].
     *
     * Order of operations (clear-flag-then-delete, matching the reserve-first
     * invariant from [hide]):
     *  1. Flip isHidden = false in DB
     *  2. Clear the reserved vaultId from DB
     *  3. Delete the .enc / .meta sidecars on disk
     *
     * If the row has no vaultId we throw [VaultException.CorruptMetadata] — this
     * indicates a pre-migration row, and [VaultMigrator] should have handled it
     * at app startup.
     */
    suspend fun unhide(item: MediaItem): Result<VaultResult> = withContext(Dispatchers.IO) {
        runCatching {
            val vaultId = item.vaultId
                ?: throw VaultException.CorruptMetadata(
                    item.uri.toString(),
                    "hidden item has no vaultId"
                )
            repository.setHidden(item.uri, false)
            repository.clearVaultId(item.uri)
            File(vaultDir, "$vaultId.enc").takeIf { it.exists() }?.delete()
            File(vaultDir, "$vaultId.meta").takeIf { it.exists() }?.delete()
            VaultResult.Unhidden as VaultResult
        }.recoverCatching { throw VaultException.UnhideFailed(it) }
    }

    /**
     * Decrypts a vault item back into a regular [Uri] usable by the viewer. The
     * plaintext is written to `cacheDir/.vault-decoded/` and the caller is expected
     * to clean up after use.
     */
    suspend fun decryptToPlaintext(vaultUri: Uri): Uri? = withContext(Dispatchers.IO) {
        try {
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            val cipherBytes = FileInputStream(vaultUri.path!!).use { it.readBytes() }
            val metaFile = File(vaultUri.path!!.removeSuffix(".enc") + ".meta")
            require(metaFile.exists()) { "Vault metadata missing: ${vaultUri.path}" }
            val metaText = metaFile.readText()
            // M15: read opaque keys; tolerate legacy plaintext "name=" / "iv=" too.
            val ivLine = metaText.lineSequence().firstOrNull { it.startsWith("i=") }
                ?: metaText.lineSequence().firstOrNull { it.startsWith("iv=") }
                ?: throw VaultException.CorruptMetadata(vaultUri.path!!, "missing iv")
            val ivEncoded = ivLine.substringAfter('=')
            val iv = android.util.Base64.decode(ivEncoded, android.util.Base64.NO_WRAP)
            val nameEncodedLine = metaText.lineSequence().firstOrNull { it.startsWith("n=") }
                ?: metaText.lineSequence().firstOrNull { it.startsWith("name=") }
            val name = nameEncodedLine?.substringAfter('=')?.let { encoded ->
                runCatching {
                    String(
                        android.util.Base64.decode(encoded, android.util.Base64.NO_WRAP),
                        Charsets.UTF_8
                    )
                }.getOrNull()
            } ?: "decrypted.bin"
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH, iv))
            val plain = cipher.doFinal(cipherBytes)
            val outDir = File(app.cacheDir, "vault-decoded").apply { mkdirs() }
            val out = File(outDir, name)
            FileOutputStream(out).use { it.write(plain) }
            Uri.fromFile(out)
        } catch (e: VaultException) {
            AppLog.e(TAG, "Vault decrypt failed (corrupt) for $vaultUri", e)
            null
        } catch (e: Throwable) {
            AppLog.e(TAG, "Vault decrypt failed for $vaultUri", e)
            null
        }
    }

    // --- internals --------------------------------------------------------

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        ks.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)
            // Don't require user auth every time — the biometric prompt is the
            // app-level gate; once the user is in, we can use the key.
            .build()
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        gen.init(spec)
        return gen.generateKey()
    }

    private fun generateVaultId(): String {
        val secureRandom = SecureRandom()
        val idBytes = ByteArray(16).also { secureRandom.nextBytes(it) }
        return android.util.Base64.encodeToString(idBytes, android.util.Base64.NO_WRAP)
            .replace("/", "_").replace("+", "-")
    }

    private fun uriHash(uri: String): String {
        val md = java.security.MessageDigest.getInstance("SHA-256")
        val digest = md.digest(uri.toByteArray(Charsets.UTF_8))
        return android.util.Base64.encodeToString(digest.copyOfRange(0, 16), android.util.Base64.NO_WRAP)
            .replace("/", "_").replace("+", "-")
    }

    enum class BiometricAvailability {
        Available,
        NoHardware,
        NotEnrolled,
        Unavailable
    }

    /**
     * Build a [BiometricPrompt] preconfigured with our preferred crypto / device-
     * credential policy.
     */
    fun promptBuilder(activity: FragmentActivity, onResult: (BiometricResult) -> Unit): BiometricPrompt {
        val executor = ContextCompat.getMainExecutor(activity)
        return BiometricPrompt(activity, executor, object : BiometricPrompt.AuthenticationCallback() {
            override fun onAuthenticationSucceeded(result: BiometricPrompt.AuthenticationResult) {
                onResult(BiometricResult.Success)
            }
            override fun onAuthenticationError(errorCode: Int, errString: CharSequence) {
                onResult(BiometricResult.Error(errorCode, errString.toString()))
            }
            override fun onAuthenticationFailed() {
                onResult(BiometricResult.Failed)
            }
        })
    }

    fun showPrompt(
        activity: FragmentActivity,
        onResult: (VaultUiEvent) -> Unit
    ) {
        val info = BiometricPrompt.PromptInfo.Builder()
            .setTitle(activity.getString(R.string.vault_unlock_title))
            .setSubtitle(activity.getString(R.string.vault_unlock_subtitle))
            .setAllowedAuthenticators(BIOMETRIC_OR_DEVICE_CREDENTIAL)
            .setConfirmationRequired(false)
            .build()
        BiometricPrompt(
            activity,
            ContextCompat.getMainExecutor(activity),
            object : BiometricPrompt.AuthenticationCallback() {
                override fun onAuthenticationSucceeded(r: BiometricPrompt.AuthenticationResult) {
                    onResult(VaultUiEvent.AuthSucceeded)
                }
                override fun onAuthenticationError(code: Int, msg: CharSequence) {
                    when (code) {
                        BiometricPrompt.ERROR_USER_CANCELED,
                        BiometricPrompt.ERROR_NEGATIVE_BUTTON,
                        BiometricPrompt.ERROR_CANCELED ->
                            onResult(VaultUiEvent.AuthCancelled)
                        else ->
                            onResult(VaultUiEvent.AuthError(code, msg.toString()))
                    }
                }
                override fun onAuthenticationFailed() {
                    onResult(VaultUiEvent.AuthFailed(activity.getString(R.string.vault_auth_failed)))
                }
            }
        ).authenticate(info)
    }

    sealed class BiometricResult {
        data object Success : BiometricResult()
        data class Error(val code: Int, val message: String) : BiometricResult()
        data object Failed : BiometricResult()
    }

    companion object {
        private const val TAG = "EncryptedPrivacyVault"
        private const val KEY_ALIAS = "smartvision_vault_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_LENGTH = 128
        private const val KEY_SIZE_BITS = 256
        private const val VAULT_DIR = ".vault"
        private const val BIOMETRIC_OR_DEVICE_CREDENTIAL =
            BiometricManager.Authenticators.BIOMETRIC_STRONG or
            BiometricManager.Authenticators.DEVICE_CREDENTIAL
    }
}